### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by joonsoome** [Samsung/vs-tools-cps#8]
We've got a task to add more icons at the toolbar menu. The existing icon pool seems so weird for example
# 1 What is default color? (Light or Dark Theme)
![image](https://github.com/user-attachments/assets/560f9577-e88f-43e2-8f76-95d721a083b9)

vs-tools-cps\src\Tizen.VisualStudio.ProjectSystem.VS\Resources\ic_tizen_package_manager.png is for dark theme, and others for white theme.

# 2 Is it necessary the edge stroke & fill at the icon?
<img width="369" alt="image" src="https://github.com/user-attachments/assets/cd8a57de-e9f8-44aa-8492-65aac365d04a">

It seems no consistency with other icons.

If I'm wrong or need more information, please don't hesitate to mail me. : joons.kim@samsung.com

https://github.sec.samsung.net/TizenIoT/samsung-tizen-OS-design/issues/342

**Comment by winstone77** [comment]
@bear8203 
Could you make an issue into internal github repo?
(https://github.sec.samsung.net/dotnet/vs-tools-cps/issues)
